### ISSUE TITLE
TinyUSDZ's matrix now row-major

### ISSUE THREAD

**Issue by syoyo** [fynv/usd2glb#1]
TinyUSDZ's matrix representation now uses row-major order, so please update tinyusdz `dev` branch. it may require some changes in usd2glb.

https://github.com/syoyo/tinyusdz/wiki/Matrix-is-row-major

**Comment by fynv** [comment]
Got it. I'll fix it tommorow. I guess my strategy would be converting them to colum-major as early as possible.
I think the last time I use a row-major matrix was in Matlab.

**Comment by fynv** [comment]
Updated TinyUSDZ & fixed main.cpp to adapt to changes.
Closing.

**Comment by syoyo** [comment]
:pray:
