### ISSUE TITLE
Give a formal license (public domain dedication)

### ISSUE THREAD

**Issue by aaronfranke** [fynv/usd2glb#2]
The README has this text:

> Toy code. No formal license. Can be freely used.

However, this isn't a very nice thing for lawyers to see. Not having an explicit license can be an obstacle for big open source projects because the terms are not explicitly clear.

Can you add a formal license? If you want to allow everything, just use The Unlicense https://choosealicense.com/licenses/unlicense/ which permits everything and does not require credit, it's a public domain dedication.

EDIT: Also, as mentioned by fire below, if you want to require giving credit, the MIT license is basically the same as The Unlicense but with a give credit clause. The Unlicense is effectively the same as MIT without this requirement.

**Comment by fire** [comment]
You can also formally license the code as Apache 2.0 or as MIT license like https://github.com/godotengine/godot/blob/master/LICENSE.txt

Thank you!

**Comment by fynv** [comment]
Added a MIT style license.
